### ISSUE TITLE
kolla not support s390x arch

### ISSUE THREAD

**Issue by Erick-shi** [james-crowley/kolla-build-logs#1]
hello, do you support kolla on s390x, I find kolla don't support s390x arch. do you have any method to resolve it. thanks.

**Comment by james-crowley** [comment]
@Erick-shi Thanks for raising this issue! I was working on porting Kolla to `s390x` and `ppc64le` durning my time at IBM. I am not longer at IBM and no longer working on this porting project.

Last time I touched this, a newer version of Ubuntu, that was just about to come out, had additional packages that were previously blocking my progress. I think some of the packages were something to do with Mysql? Or maybe some sort of database, I can't remember off the top of my head.

What I would suggest is trying to build Kolla for `s390x` using the most up to date version of Ubuntu. It might just work! If not or if you run into any issues, I would recommend hoping on to the chat the devs used. They were pretty active on the chat!

**Comment by Erick-shi** [comment]
@james-crowley  thank you, I think I can't do it.. so I only wait comm to support it...
